### ISSUE TITLE
在linux环境下面导入模型的路径不对

### ISSUE THREAD

**Issue by swat199538** [Lockey-J/DdddOcrSharp#3]
`using var ddddocr = new DDDDOCR(DdddOcrMode.ClassifyOld);`

ClassifyOld模式对应的模型文件不存在:/var/www/html/onnxs\common_old.onnx

**Comment by Lockey-J** [comment]
Path.Combine(AppDomain.CurrentDomain.BaseDirectory, Mode.GetDescription());这个是要把自带的模型放在主程序下面的

**Comment by Lockey-J** [comment]
你在linux里调试输出一下。看看是什么路径。

**Comment by shusongLu** [comment]
这个问题其实是枚举的Description路径不对,改成[Description("onnxs/common_old.onnx")]反斜杠就可以了
